class Version:
    def __init__(self, version_string: str, *, partial: bool = False) -> None: ...
    def __lt__(self, other: Version) -> bool: ...
    def __le__(self, other: Version) -> bool: ...
    def __gt__(self, other: Version) -> bool: ...
    def __ge__(self, other: Version) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class SimpleSpec:
    def __init__(self, expression: str) -> None: ...
    def match(self, version: Version) -> bool: ...

class NpmSpec:
    def __init__(self, expression: str) -> None: ...
    def match(self, version: Version) -> bool: ...
